version: '3.7'

services:
  nestjs:
    build:
      context: ./nest-ecommerce
    container_name: nestjs-container
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      - NODE_ENV=production
    depends_on:
      - nuxt

  nuxt:
    build:
      context: ./ecom-frontend
    container_name: nuxt-container
    ports:
      - "3001:3000"
    networks:
      - app-network
    environment:
      - NODE_ENV=production

networks:
  app-network:
    driver: bridge
